<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBAConei\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBAConei/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBAConei.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBAConei\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBAConei\App_KernelDevDebugContainer([
    'container.build_hash' => 'BAConei',
    'container.build_id' => '676c672d',
    'container.build_time' => 1666338934,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBAConei');
